{% set name = "oracledb" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oracledb-{{ version }}.tar.gz
  sha256: 63d17ebb95f9129d0ab9386cb632c9e667e3be2c767278cc11a8e4585468de33

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=40.6.0
    - wheel
    - cython
    - pip
  run:
    - python
    - cryptography >=3.2.1

test:
  imports:
    - oracledb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://oracle.github.io/python-oracledb
  summary: Python interface to Oracle Database
  description: |
    python-oracledb is a Python programming language extension module allowing Python programs to connect to Oracle Database. 
    It is the renamed, new major release of the popular cx_Oracle driver.
  dev_url: https://github.com/oracle/python-oracledb
  doc_url: https://python-oracledb.readthedocs.io
  license: Apache-2.0 OR UPL-1.0
  license_family: Apache
  license_file:
    - LICENSE.txt
    - NOTICE.txt

extra:
  recipe-maintainers:
    - xylar
