{% set name = "oracledb" %}
{% set version = "4.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oracledb-{{ version }}.tar.gz
  sha256: 0a380ab72853487ea2764c5df772f35026b4219868fc3eba68e193c9aea230ac

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=77.0.0
    - cython >=3.2,<4
  run:
    - python
    - cryptography >=3.2.1
    - typing_extensions >=4.14.0

test:
  imports:
    - oracledb
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Tests require connection to DB
    # - pytest -v tests

about:
  home: https://oracle.github.io/python-oracledb
  summary: Python interface to Oracle Database
  description: |
    python-oracledb is a Python programming language extension module allowing Python programs to connect to Oracle Database.
    It is the renamed, new major release of the popular cx_Oracle driver.
  dev_url: https://github.com/oracle/python-oracledb
  doc_url: https://python-oracledb.readthedocs.io
  license: Apache-2.0 OR UPL-1.0
  license_family: Apache
  license_file:
    - LICENSE.txt
    - NOTICE.txt

extra:
  recipe-maintainers:
    - xylar
